### ISSUE TITLE
Job data object converted to array

### ISSUE THREAD

**Issue by LubosRemplik** [josegonzalez/php-queuesadilla#58]
When I add object into data, e.g. Cake\ORM\Entity and then when I getting this data via $entity = $job->data('entity'), $entity is array while I expect Entity object.

Is this bug or my wrong assumption?

**Comment by josegonzalez** [comment]
That seems right. Since we enqueue it, its probably calling `toArray()` on the entity, as we don't ship serialized objects.

I would instead recommend queuing the minimal amount of data to run the job, such as just the record ID, and then retrieving the full dataset from your datastore. This keeps job payloads small and ensures you aren't dealing with potentially stale data.

**Comment by LubosRemplik** [comment]
Makes sense, thanks!
